# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Think before you die
email: whywayaway@gmail.com
description: >
  This blog concerns versatile subjects pulling apart common notions with the skill of a surgeon.
  Furthermore, it is also a travel and adventure journal kept by backpacker, explorer and digital nomad.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://szacho.me" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  szacho
permalink: /:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  medium_feed:
    output: true
    permalink: /medium/:name

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
